version: 2

sources:
  - name: sc1
    database: KRISHDB27  
    schema: KRISHSCH  
    tables:
      - name: EMP
      - name: employees
      - name: SALES
      - name: SALES2
      - name: CUST
      - name: ext_employee_data